Logging and Exception Management assignment
Sartaj-ti/jtu-22-logging-and-exception-management-assignment pull request #1
Opened 2022-12-13 16:52 UTC by Sartaj-ti

2022-12-15 05:20 UTC, naman-TI requested changes
This is not approved. Need to make changes to 3 more files and concrete logging/exception handling is not present in the 5 files changed.

2022-12-15 05:20 UTC, naman-TI commented on fast_api_als/services/enrich_lead.py
> +        raise TypeError(f'{adf_json} cannot be converted to object')
check for KeyError as well

2022-12-15 05:20 UTC, naman-TI commented on fast_api_als/routers/submit_lead.py
> +        raise fastapi.HTTPException(status_code=404, detail='Wrong API key')
should it be 400?

2022-12-15 05:20 UTC, naman-TI commented on fast_api_als/routers/submit_lead.py
>          res = sqs_helper_session.send_message(message)
always need to handle exceptions when using third party APIs

2022-12-15 05:20 UTC, naman-TI commented on fast_api_als/routers/submit_lead.py
>          res = sqs_helper_session.send_message(message)
line 215 also and all instances where AWS apis are being used

2022-12-15 06:25 UTC, Sartaj-ti commented
Okk sir, I will make the necessary changes and submit again.

On Thu, Dec 15, 2022, 10:50 Naman Yadav ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> This is not approved. Need to make changes to 3 more files and concrete
> logging/exception handling is not present in the 5 files changed.
> ------------------------------
>
> In fast_api_als/services/enrich_lead.py
> <https://github.com/Sartaj-ti/jtu-22-logging-and-exception-management-assignment/pull/1#discussion_r1049223440>
> :
>
> > \ No newline at end of file
> +    adf_obj = json.loads(adf_json, object_hook=lambda d: SimpleNamespace(**d))
> +    if not adf_obj:
> +        raise TypeError(f'{adf_json} cannot be converted to object')
>
> check for KeyError as well
> ------------------------------
>
> In fast_api_als/routers/submit_lead.py
> <https://github.com/Sartaj-ti/jtu-22-logging-and-exception-management-assignment/pull/1#discussion_r1049223824>
> :
>
> > @@ -38,7 +38,7 @@ async def submit(file: Request, apikey: APIKey = Depends(get_api_key)):
>
>      if not db_helper_session.verify_api_key(apikey):
>          # throw proper fastpi.HTTPException
> -        pass
> +        raise fastapi.HTTPException(status_code=404, detail='Wrong API key')
>
> should it be 400?
> ------------------------------
>
> In fast_api_als/routers/submit_lead.py
> <https://github.com/Sartaj-ti/jtu-22-logging-and-exception-management-assignment/pull/1#discussion_r1049223970>
> :
>
> > @@ -197,6 +197,8 @@ async def submit(file: Request, apikey: APIKey = Depends(get_api_key)):
>              }
>          }
>          res = sqs_helper_session.send_message(message)
>
> always need to handle exceptions when using third party APIs
> ------------------------------
>
> In fast_api_als/routers/submit_lead.py
> <https://github.com/Sartaj-ti/jtu-22-logging-and-exception-management-assignment/pull/1#discussion_r1049224233>
> :
>
> > @@ -197,6 +197,8 @@ async def submit(file: Request, apikey: APIKey = Depends(get_api_key)):
>              }
>          }
>          res = sqs_helper_session.send_message(message)
>
> line 215 also and all instances where AWS apis are being used
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Sartaj-ti/jtu-22-logging-and-exception-management-assignment/pull/1#pullrequestreview-1218597497>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4WHLJORYNVPJCWRUHBPEJTWNKTCNANCNFSM6AAAAAAS5N56KM>
> .
> You are receiving this because you authored the thread.Message ID:
> <Sartaj-ti/jtu-22-logging-and-exception-management-assignment/pull/1/review/1218597497
> @github.com>
>

2022-12-16 07:56 UTC, naman-TI commented on fast_api_als/utils/adf.py
> +    except Exception as e:
if this is KeyError, why do you need to catch the generic 'Exception'

2022-12-16 07:57 UTC, closed without merging